import dynamic from "next/dynamic";
import Head from "next/head";
import Appointment from "../components/Appointment";
import Footer from "../components/Footer";
import Loader from "../components/Loader";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
