import dynamic from "next/dynamic";
import Head from "next/head";
const Banner = dynamic(() => import("../components/Banner"));
const Info = dynamic(() => import("../components/Info"));
const HomeMenu = dynamic(() => import("../components/HomeMenu"));
const HomeSpecial = dynamic(() => import("../components/HomeSpecial"));
const Features = dynamic(() => import("../components/Features"));
const Post = dynamic(() => import("../components/Post"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Info />
      <HomeMenu />
      <Features />
      <HomeSpecial />
      <Post />
    </>
  );
}
